version: "3.8"

services:
  frontend:
    image: hmurafique/ecom-frontend:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 2

  catalog:
    image: hmurafique/catalog-service:latest
    environment:
      - PORT=5000
    deploy:
      replicas: 2

  cart:
    image: hmurafique/cart-service:latest
    environment:
      - REDIS_HOST=redis
    deploy:
      replicas: 2

  order:
    image: hmurafique/order-service:latest
    environment:
      - DB_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
    deploy:
      replicas: 2

  payment:
    image: hmurafique/payment-service:latest
    deploy:
      replicas: 1

  redis:
    image: redis:6-alpine
    deploy:
      replicas: 1

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 1

volumes:
  db_data:
